# Generated by Django 6.1.1 on 2026-10-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_sociallink_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='company',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='company_icon_svg',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='founder',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='site_icon_svg',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
