# Generated by Django 6.1.1 on 2026-10-05 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_about_address_about_company_about_company_icon_svg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='social_icon',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
