# Generated by Django 6.1.1 on 2026-10-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_sociallink_social_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='company_icon_svg',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='site_icon_svg',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
